apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtask-deployment
spec:
  replicas: 1
  selector: 
    matchExpressions:
      - key: app
        operator: In
        values:
        - addtask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata:
      labels: 
        app: addtask
      name: addtask-pod
    spec:
      containers:
      - env:
        - name: CONNECTION_STRING
          valueFrom: 
            secretKeyRef:
                key: connectionString
                name: todo-secret
        image: mehul005a/addtasks-microtodo
        name: addtask-container
        ports:
        - containerPort: 8000
          #hostPort: 8081