apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  connectionString: RHJpdmVyPXtPREJDIERyaXZlciAxNyBmb3IgU1FMIFNlcnZlcn07U2VydmVyPXRjcDpkaGFua3ViZW5ldC5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0RhdGFiYXNlPWRoYW4tS3ViZXItZGF0YWJhc2U7VWlkPXNxbGFkbWluO1B3ZD1LYWlkYXBhc3N3b3JkQDk4NztFbmNyeXB0PXllcztUcnVzdFNlcnZlckNlcnRpZmljYXRlPW5vO0Nvbm5lY3Rpb27CoFRpbWVvdXQ9MzA7
