apiVersion: apps/v1
kind: Deployment
metadata:
  name: deletetask-deployment
spec:
  replicas: 1
  selector: 
    matchExpressions:
      - key: app
        operator: In
        values:
        - deleteTask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata:
      labels: 
        app: deleteTask
      name: deleteTaskpod
    spec:
      containers:
      - env:
        - name: CONNECTION_STRING
          valueFrom: 
            secretKeyRef:
                key: connectionString
                name: todo-secret
        image: mehul005a/deletetasks-microtodo
        name: deletetaskcontainer
        ports:
        - containerPort: 8000
          #hostPort: 8082