apiVersion: apps/v1
kind: Deployment
metadata:
  name: gettask-deployment
spec:
  replicas: 1
  selector: 
    matchExpressions:
      - key: app
        operator: In
        values:
        - gettask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata:
      labels: 
        app: gettask
      name: gettask-pod
    spec:
      containers:
      - env:
        - name: CONNECTION_STRING
          value: Driver={ODBC Driver 17 for SQL Server};Server=tcp:dhankubenet.database.windows.net,1433;Database=dhan-Kuber-database;Uid=sqladmin;Pwd=Kaidapassword@987;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
        image: mehul005a/gettasks-microtodo
        name: gettask-container
        ports:
        - containerPort: 8000
          #hostPort: 8083